import 'package:flutter/material.dart';

class AppLocalizations {
  final String localeName;

  AppLocalizations(this.localeName);

  static AppLocalizations of(BuildContext context) {
    // A simple hack to get the localized strings without depending on standard Localizations widgets.
    // In a real app we'd use LocalizationsDelegate, but this works nicely for a prototype.
    final locale = Localizations.localeOf(context).languageCode;
    return AppLocalizations(locale);
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'farm_activity': 'Farm Activity',
      'farm_activity_log': 'Farm Activity Log',
      'activity_history': 'Activity History',
      'add_activity': 'Add Activity',
      'activity_type': 'Activity Type',
      'general_farm_activity': 'General Farm Activity',
      'delete_activity_confirm': 'Do you want to delete this activity?',
      'no_farm_activities_yet': '📋 No farm activities yet',
      'record_farm_activities_prompt': 'Record your farm activities to keep a simple history.',
      'irrigation': 'Irrigation',
      'fertilizer_application': 'Fertilizer Application',
      'pest_control': 'Pest Control',
      'weed_control': 'Weed Control',
      'spraying': 'Spraying',
      'field_inspection': 'Field Inspection',
      'harvesting': 'Harvesting',
      'selling': 'Selling',
      'growth_tracking': 'Growth Tracking',
      'add_growth_update': 'Add Growth Update',
      'growth_stage': 'Growth Stage',
      'no_growth_updates_yet': '🌱 No growth updates yet',
      'add_an_update_to_keep_track': 'Add an update to keep track of your crop growth.',
      'seed_sowing': 'Seed / Sowing',
      'germination': 'Germination',
      'vegetative_growth': 'Vegetative Growth',
      'flowering': 'Flowering',
      'fruit_grain_development': 'Fruit / Grain Development',
      'maturity': 'Maturity',
      'harvest_ready': 'Harvest Ready',
      'delete_update_confirm': 'Do you want to delete this growth update?',
      'general_farm_reminder': 'General Farm Reminder',
      'delete_reminder_confirm': 'Do you want to delete this reminder?',
      'upcoming': 'Upcoming',
      'overdue': 'Overdue',
      'completed': 'Completed',
      'mark_as_completed': 'Mark as Completed',
      'delete': 'Delete',
      'add_time': 'Add Time',
      'clear_time': 'Clear Time',
      'no_reminders_yet': '🔔 No reminders yet',
      'create_a_reminder': 'Create a reminder for your farm activities.',
      'variety': 'Variety',
      'sowing_date': 'Sowing Date',
      'expected_harvest_date': 'Expected Harvest Date',
      'farm_area': 'Farm Area',
      'no_crops_added_yet': '🌱 No crops added yet',
      'add_your_crops': 'Add your crops to keep your farm information organized.',
      'remove_crop_confirm': 'Do you want to remove this crop?',
      'add_crop': '+ Add Crop',
      'edit_crop': '✏️ Edit Crop',
      'crop_name': 'Crop Name',
      'save': 'Save',
      'cancel': 'Cancel',
      'remove': '🗑️ Remove',
      'edit': '✏️ Edit',
      'use_current_location': '📍 Use Current Location',
      'location_unavailable': 'Location unavailable',
      'location_saved': 'Location saved',
      'location_updated': 'Location updated',
      'location_permission_denied': 'Location permission denied. Please enter manually.',

      'village': 'Village',
      'district': 'District',
      'state': 'State',
      'my_crops': 'My Crops',
      'remove_crop': 'Remove',
      'acres': 'Acres',
      'hectares': 'Hectares',
      'irrigation_type': 'Irrigation Type',
      'farming_type': 'Farming Type',
      'organic': 'Organic',
      'conventional': 'Conventional',
      'mixed': 'Mixed',
      'other': 'Other',
      'rainfed': 'Rainfed',
      'borewell': 'Borewell',
      'canal': 'Canal',
      'drip': 'Drip',
      'sprinkler': 'Sprinkler',
      'edit_profile': 'Edit Profile',
      'complete_profile_prompt': 'Complete your farmer profile\nAdd your farm details to personalize RythuMitra.',
      'complete_profile': 'Complete Profile',
      'change_language': 'Change Language',

      'home_greeting': 'Hello!',
      'home_title': 'RythuMitra AI',
      'home_subtitle': 'Your Smart Farming Assistant',
      'ask_anything': 'Ask me anything about your farming',
      'quick_actions': 'Quick Actions',
      'quick_weather': 'Weather',
      'quick_prices': 'Market Prices',
      'quick_diagnosis': 'Crop Diagnosis',
      'quick_schemes': 'Gov Schemes',
      'nav_home': 'Home',
      'nav_ai': 'AI Assistant',
      'nav_farm': 'My Farm',
      'nav_tasks': 'Tasks',
      'nav_more': 'More',
      'ai_thinking': '🤖 RythuMitra is thinking...',
      'speak_button': 'Listen',
      'speaking_button': 'Speaking...',
      'voice_unavailable': 'Voice is not currently available for this language on your device.',
      'mic_error': 'Could not start microphone. Please check permissions.',
      'sug_crop': '🌱 My crop has a problem',
      'sug_weather': '🌦️ Tell me today\'s weather',
      'sug_water': '💧 When should I water my crop?',
      'sug_price': '📈 What is the market price?',
      'ai_greeting': 'Hello! I am RythuMitra.',
      'ai_help': 'You can ask me anything about your farming.',
      'ai_title': '🤖 RythuMitra AI Assistant',
      'profile_setup_title': 'Profile Setup',
      'farmer_profile': 'Farmer Profile',
      'farm_profile': 'Farm Profile',
      'farmer_name': 'Farmer Name',
      'location': 'Location',
      'farm_name': 'Farm Name (Optional)',
      'land_size': 'Land Size',
      'land_unit': 'Unit',
      'farm_type': 'Farm Type',
      'current_crops': 'Current Crops',
      'skip_for_now': 'Skip for now',
      'no_farm_profile': 'Add your farm details to help RythuMitra understand your farming.',
      'no_crops': 'You haven\'t added any crops yet.',
      'memory_title': '🧠 What RythuMitra Knows About My Farm',
      'planting_date': 'Planting Date',
      'notes': 'Notes',
      'status': 'Status',
      'growing': 'Growing',
      'needs_attention': 'Needs Attention',
      'info_incomplete': 'Information Incomplete',
      'harvested': 'Harvested',
      'ask_rythumitra_crop': '🤖 Ask RythuMitra About This Crop',
      'crop_details': 'Crop Details',
      'harvested_crops': 'Harvested Crops',
      'seedling': 'Seedling',
      'vegetative': 'Vegetative',
      'fruiting': 'Fruiting / Grain Development',
      'not_sure': 'Not Sure',
      'add_more_details': 'Add more details to help RythuMitra understand this crop better.',
      // Scanner / Vision Feature
      'crop_photo': 'Crop Photo',
      'analyzing_crop': '🔍 RythuMitra is checking your crop...',
      'which_crop': 'Which crop is this?',
      'select_crop': 'Select a crop',
      'optional_notes': 'Optional Notes',
      'describe_problem': 'e.g. Leaves are turning yellow',
      'retake': 'Retake',
      'analyze': 'Analyze',
      'analysis_result': 'Analysis Result',
      'save_result': 'Save Result',
      'stop_audio': 'Stop',
      'listen_audio': 'Listen',
      'ai_uncertainty_warning': 'The image alone may not be enough for a confirmed diagnosis. This is an AI observation.',
      'possible_issues': '⚠️ Possible Causes',
      'visible_symptoms': '👀 What was observed',
      'recommended_next_steps': '🌱 What you can check',
      'when_to_seek_expert': 'When to seek expert help',
      'take_another_photo': 'Take Another Photo',
      'scan_crop_problem': 'Scan Crop Problem',
      'take_photo': 'Take Photo',
      'choose_from_gallery': 'Choose From Gallery',
      'scan_this_crop': 'Scan This Crop',
      'previous_checks': 'Previous Checks',
      'analysis_failed': 'Unable to analyze the crop photo right now. Please try again.',
      'scan_saved_successfully': 'Scan result saved successfully.',
      'crop_health': 'Crop Health',
      'check_crop': 'Check Crop',
      'crop_analysis': 'Crop Analysis',
      'observation': 'Observation',
      'advice': 'Advice',
      'precautions': 'Precautions',
      'no_crop_analysis': 'No crop analysis is available right now',
      'crop_analysis_unavailable': 'Crop analysis is currently unavailable',
      'report_history': 'Report History',
      // Health History
      'crop_health_history': 'Crop Health History',
      'no_health_checks_yet': 'No crop health checks yet.\nTake a photo if you notice a problem.',
      'status_monitoring': 'Monitoring',
      'status_improved': 'Improved',
      'status_still_has_problem': 'Still Has Problem',
      'status_not_checked_yet': 'Not Checked Yet',
      'initial_scan': 'Initial Scan',
      'timeline': 'Timeline',
      'no_follow_ups': 'No follow-ups yet.',
      'farmer_update': 'Farmer Update',
      'ai_analysis': 'AI Analysis',
      'add_follow_up': 'Add Follow-up',
      'add_note': 'Add a note',
      'add_photo': 'Add Photo',
      'analyze_new_photo': 'Analyze new photo with AI',
      'ask_rythumitra_history': '🤖 Ask RythuMitra About This History',
      'delete_record': 'Delete Record',
      'delete_confirm_desc': 'Are you sure you want to delete this health record and all its follow-ups? This action cannot be undone.',
      // Weather Feature
      'weather_load_error': 'Unable to get weather information right now.',
      'weather_clear_sky': 'Clear sky',
      'weather_partly_cloudy': 'Partly cloudy',
      'weather_fog': 'Fog',
      'weather_drizzle': 'Drizzle',
      'weather_rain': 'Rain',
      'weather_snow': 'Snow',
      'weather_rain_showers': 'Rain showers',
      'weather_thunderstorm': 'Thunderstorm',
      'weather_cloudy': 'Cloudy',
      'weather_unknown': 'Unknown',
      'current_weather': 'Current Weather',
      'humidity': 'Humidity',
      'wind': 'Wind',
      'rain': 'Rain',
      'explain_weather_farm': '🤖 Explain Weather for My Farm',
      'forecast': 'Forecast',
      'last_updated': 'Last Updated',
      'today': 'Today',
      'change_location': 'Change Location',
      'enter_town_name': 'Enter town or district name',
      'getting_weather_info': 'Getting weather information...',
      'retry': 'Retry',
      // Alerts & Reminders
      'weather_alerts': 'Weather Alerts',
      'no_alerts': 'No important alerts right now.',
      'farm_reminders': 'Farm Reminders',
      'add_reminder': 'Add Reminder',
      'no_reminders': 'No reminders set.',
      'enter_title_error': 'Please enter a title',
      'reminder_title': 'Reminder Title',
      'date': 'Date',
      'time': 'Time',
      'updates': 'Updates',
      'alert_rain_title': 'Rain Now',
      'alert_rain_desc': 'It is currently raining in your area.',
      'alert_temp_title': 'High Temperature Now',
      'alert_temp_desc': 'Temperatures are currently very high.',
      'alert_wind_title': 'Strong Wind',
      'alert_wind_desc': 'Strong winds are present in your area.',
      'alert_rain_forecast_title': 'Rain Expected',
      'alert_rain_forecast_desc': 'Rain is forecast in your area soon.',
      'alert_temp_forecast_title': 'High Temperature Expected',
      'alert_temp_forecast_desc': 'High temperature is forecast. Check the weather details for your farm.',
      'alert_temp_change_title': 'Temperature Change',
      'alert_temp_change_desc': 'A significant temperature change is expected soon.',
      'ask_rythumitra': 'Ask RythuMitra',
      // Market Prices
      'market_prices': 'Market Prices',
      'market_update': 'Market Update',
      'view_market': 'View Market',
      'search_crop': 'Search Crop (e.g., Tomato)',
      'data_unavailable': 'Market price data unavailable.',
      'check_market_price': 'Check Market Price',
      'no_market_price_found': 'No market price found',
      'no_market_price_desc': 'No market price was found for this crop and selected location.',
      'try_again': 'Try Again',
      'search_another_crop': 'Search Another Crop',
      'market_unavailable': 'Market information is temporarily unavailable.',
      'ai_welcome': 'Namaste! I am RythuMitra AI. How can I help you with your farm?',
      'sug_my_crop': '🌱 My Crop',
      'sug_weather_quick': '🌦️ Weather',
      'sug_market_price': '💰 Market Price',
      'sug_crop_problem': '🐛 Crop Problem',
      'sug_irrigation': '💧 Irrigation',
      'sug_farming_advice': '🌾 Farming Advice',
      'ask_placeholder': 'Ask RythuMitra...',
      'send': 'Send',
      'clear_chat': '🗑️ Clear Chat',
      'clear_chat_confirm': 'Clear this conversation?',
      'clear': 'Clear',
      'ai_unavailable': 'RythuMitra AI is temporarily unavailable. Please try again.',
      'ai_conn_unavailable': '🔴 AI connection unavailable',
      'farm_location': 'Farm Location',
      'add_farm_location_weather': 'Add your farm location to view local weather.',
      'go_to_farm_location': 'Go to Farm Location',
      'weather_unavailable': 'Weather information is currently unavailable.',
      'offline_weather_warning': 'Showing previously cached data. You are offline.',
      'no_crops_yet': 'No crops added yet.',
      'add_crop_market': 'Add Crop',
      'getting_market_info': 'Getting market information...',
      'offline_market_warning': 'Market information is currently unavailable.',
      'no_market_data': 'No market data available right now.',
      'minimum_price': 'Minimum Price',
      'maximum_price': 'Maximum Price',
      'modal_price': 'Modal Price',
      'reported_on': 'Reported On:',
      'unit_label': 'Unit:',
      // Farm Expenses
      'farm_expenses': 'Farm Expenses',
      'total_expenses': 'Total Expenses',
      'expense_history': 'Expense History',
      'add_expense': 'Add Expense',
      'expense_type': 'Expense Type',
      'amount': 'Amount',
      'seeds': 'Seeds',
      'fertilizer': 'Fertilizer',
      'pesticides': 'Pesticides',
      'labour': 'Labour',
      'machinery': 'Machinery',
      'transport': 'Transport',
      'electricity': 'Electricity',
      'general_farm_expense': 'General Farm Expense',
      'no_expenses_recorded_yet': 'No expenses recorded yet',
      'add_your_farm_expenses': 'Add your farm expenses to keep track of your spending.',
      'delete_expense_confirm': 'Do you want to delete this expense?',
      'all': 'All',
      'invalid_amount': 'Invalid amount',
      'expense_other': 'Other',
      'save_action': 'Save',
      'cancel_action': 'Cancel',
      'edit_action': 'Edit',
      'delete_action': 'Delete',
      // Farm Income
      'farm_income': 'Farm Income',
      'sales': 'Sales',
      'total_income': 'Total Income',
      'sales_history': 'Sales History',
      'add_sale': 'Add Sale',
      'quantity': 'Quantity',
      'quantity_unit': 'Quantity Unit',
      'selling_price': 'Selling Price',
      'price_unit': 'Price Unit',
      'buyer': 'Buyer',
      'market_name': 'Market',
      'sale_date': 'Sale Date',
      'kg': 'Kg',
      'quintal': 'Quintal',
      'ton': 'Ton',
      'rs_per_kg': '₹ / Kg',
      'rs_per_quintal': '₹ / Quintal',
      'rs_per_ton': '₹ / Ton',
      'total_sale_value': 'Total Sale Value',
      'no_sales_recorded_yet': 'No sales recorded yet',
      'record_your_crop_sales': 'Record your crop sales to keep track of your farm income.',
      'delete_sale_confirm': 'Do you want to delete this sale?',
      // Farm Financial Summary
      'farm_financial_summary': 'Farm Financial Summary',
      'net_balance': 'Net Balance',
      'crop_summary': 'Crop Summary',
      'all_time': 'All Time',
      'this_month': 'This Month',
      'custom_date_range': 'Custom Date Range',
      'no_financial_records_yet': 'No financial records yet',
      'add_income_expenses_prompt': 'Add your farm income and expenses to see your farm summary',
      'add_income': 'Add Income',
      'select_date_range': 'Select Date Range',
      'from_date': 'From',
      'to_date': 'To',
      // Farm Calendar
      'farm_calendar': 'Farm Calendar',
      'previous_month': 'Previous Month',
      'next_month': 'Next Month',
      'selected_date': 'Selected Date',
      'no_farm_activities_for_this_date': 'No farm activities for this date',
      'event_details': 'Event Details',
      'event_type_reminder': 'Reminder',
      'event_type_activity': 'Activity',
      'event_type_growth': 'Crop Growth',
      'event_type_photo': 'Crop Photo',
      // Backup & Restore
      'backup_restore': 'Data Backup & Restore',
      'create_backup': 'Create Backup',
      'restore_backup': 'Restore Backup',
      'backup_success': 'Backup Created Successfully',
      'restore_farm_data': 'Restore Your Farm Data',
      'restoring_data': 'Restoring Your Farm Data...',
      'invalid_backup_file': 'Invalid Backup File',
      'continue_btn': 'Continue',
      'backup_version': 'Backup Version',
      'backup_date': 'Backup Date',
      'backup_warning': 'This backup may replace your current farm data',
      'backup_not_supported': 'This backup was created using a newer version of RythuMitra.',
      'restore_success': 'Your farm data was restored successfully.',
      'backup_photos_not_included': 'Note: Crop photos are not included in the backup.',
      // Emergency Help
      'emergency_help': 'Emergency Help',
      'important_contacts': 'Important Contacts',
      'add_contact': 'Add Contact',
      'contact_name': 'Contact Name',
      'phone_number': 'Phone Number',
      'contact_category': 'Category',
      'contact_notes': 'Notes',
      'call_btn': 'Call',
      'edit_btn': 'Edit',
      'delete_btn': 'Delete',
      'cancel_btn': 'Cancel',
      'quick_access': 'Quick Access',
      'no_contacts_yet': 'No important contacts added yet.',
      'delete_contact_confirm': 'Do you want to delete this contact?',
      'cat_agriculture_officer': 'Agriculture Officer',
      'cat_veterinary_help': 'Veterinary Help',
      'cat_family': 'Family',
      'cat_friend': 'Friend',
      'cat_medical_help': 'Medical Help',
      'cat_emergency': 'Emergency',
      'cat_other': 'Other',
      // Daily Farm Planner
      'planner_title': 'Daily Farm Planner',
      'planner_todays_tasks': 'Today\'s Tasks',
      'planner_upcoming_tasks': 'Upcoming Tasks',
      'planner_completed_tasks': 'Completed Tasks',
      'planner_add_task': 'Add Task',
      'planner_task_title': 'Task Title',
      'planner_select_date': 'Select Date',
      'planner_select_time': 'Select Time',
      'planner_related_crop': 'Related Crop',
      'planner_notes': 'Notes',
      'planner_completed': 'Completed',
      'planner_pending': 'Pending',
      'planner_overdue': 'Overdue',
      'planner_delete_task': 'Delete Task',
      'planner_delete_confirm': 'Do you want to delete this task?',
      'planner_daily_progress': 'Daily Progress',
      'planner_total_tasks': 'Total Tasks',
      'planner_remaining': 'Remaining',
      'planner_today': 'Today',
      'planner_tomorrow': 'Tomorrow',
      'planner_this_week': 'This Week',
      'planner_all_tasks': 'All Tasks',
      'crop_dashboard': 'Crop Dashboard',
      'net_crop_balance': 'Net Crop Balance',
      'dashboard_summary': 'Dashboard Summary',
      'dashboard_records': 'Records',
      'dashboard_activities': 'Activities',
      'dashboard_tasks': 'Tasks',
      'dashboard_reminders': 'Reminders',
      'dashboard_expenses': 'Expenses',
      'dashboard_income': 'Income',
      'dashboard_photos': 'Photos',
    },
    'te': {
      'farm_activity': 'పొలం కార్యకలాపాలు',
      'farm_activity_log': 'పొలం కార్యకలాపాల లాగ్',
      'activity_history': 'కార్యకలాపాల చరిత్ర',
      'add_activity': 'కార్యకలాపాన్ని జోడించండి',
      'activity_type': 'కార్యకలాపం రకం',
      'general_farm_activity': 'సాధారణ పొలం కార్యకలాపం',
      'delete_activity_confirm': 'మీరు ఈ కార్యకలాపాన్ని తొలగించాలనుకుంటున్నారా?',
      'no_farm_activities_yet': '📋 ఇంకా పొలం కార్యకలాపాలు లేవు',
      'record_farm_activities_prompt': 'సాధారణ చరిత్రను ఉంచడానికి మీ పొలం కార్యకలాపాలను రికార్డ్ చేయండి.',
      'irrigation': 'నీటిపారుదల',
      'fertilizer_application': 'ఎరువుల అప్లికేషన్',
      'pest_control': 'తెగులు నియంత్రణ',
      'weed_control': 'కలుపు నియంత్రణ',
      'spraying': 'పిచికారీ',
      'field_inspection': 'పొలం తనిఖీ',
      'harvesting': 'కోత',
      'selling': 'అమ్మకం',
      'growth_tracking': 'పంట పెరుగుదల ట్రాకింగ్',
      'add_growth_update': 'పెరుగుదల నవీకరణను జోడించండి',
      'growth_stage': 'పెరుగుదల దశ',
      'no_growth_updates_yet': '🌱 ఇంకా పెరుగుదల నవీకరణలు లేవు',
      'add_an_update_to_keep_track': 'మీ పంట పెరుగుదలను ట్రాక్ చేయడానికి నవీకరణను జోడించండి.',
      'seed_sowing': 'విత్తనం / విత్తడం',
      'germination': 'మొలకెత్తడం',
      'vegetative_growth': 'శాకీయ పెరుగుదల',
      'flowering': 'పూత',
      'fruit_grain_development': 'పండు / గింజ అభివృద్ధి',
      'maturity': 'పక్వదశ',
      'harvest_ready': 'కోతకు సిద్ధం',
      'delete_update_confirm': 'మీరు ఈ పెరుగుదల నవీకరణను తొలగించాలనుకుంటున్నారా?',
      'general_farm_reminder': 'సాధారణ వ్యవసాయ రిమైండర్',
      'delete_reminder_confirm': 'మీరు ఈ రిమైండర్‌ని తొలగించాలనుకుంటున్నారా?',
      'upcoming': 'రాబోయేవి',
      'overdue': 'గడువు ముగిసినవి',
      'completed': 'పూర్తయింది',
      'mark_as_completed': 'పూర్తయినట్లు గుర్తు పెట్టు',
      'delete': 'తొలగించు',
      'add_time': 'సమయం జోడించు',
      'clear_time': 'సమయం తీసివేయి',
      'no_reminders_yet': '🔔 ఇంకా రిమైండర్‌లు లేవు',
      'create_a_reminder': 'మీ వ్యవసాయ కార్యకలాపాల కోసం రిమైండర్‌ని సృష్టించండి.',
      'variety': 'రకం',
      'sowing_date': 'విత్తిన తేదీ',
      'expected_harvest_date': 'ఆశించిన పంట తేదీ',
      'farm_area': 'పంట విస్తీర్ణం',
      'no_crops_added_yet': '🌱 ఇంకా పంటలు జోడించబడలేదు',
      'add_your_crops': 'మీ వ్యవసాయ సమాచారాన్ని ఆర్గనైజ్ చేయడానికి మీ పంటలను జోడించండి.',
      'remove_crop_confirm': 'మీరు ఈ పంటను తీసివేయాలనుకుంటున్నారా?',
      'add_crop': '+ పంటను జోడించు',
      'edit_crop': '✏️ పంటను సవరించు',
      'crop_name': 'పంట పేరు',
      'save': 'భద్రపరుచు',
      'cancel': 'రద్దు చేయి',
      'remove': '🗑️ తీసివేయి',
      'edit': '✏️ సవరించు',
      'use_current_location': '📍 ప్రస్తుత స్థానాన్ని ఉపయోగించండి',
      'location_unavailable': 'స్థానం అందుబాటులో లేదు',
      'location_saved': 'స్థానం సేవ్ చేయబడింది',
      'location_updated': 'స్థానం నవీకరించబడింది',
      'location_permission_denied': 'స్థాన అనుమతి నిరాకరించబడింది. దయచేసి మాన్యువల్‌గా నమోదు చేయండి.',

      'village': 'గ్రామం',
      'district': 'జిల్లా',
      'state': 'రాష్ట్రం',
      'my_crops': 'నా పంటలు',
      'remove_crop': 'తొలగించు',
      'acres': 'ఎకరాలు',
      'hectares': 'హెక్టార్లు',
      'irrigation_type': 'నీటి పారుదల రకం',
      'farming_type': 'వ్యవసాయ రకం',
      'organic': 'సేంద్రియ',
      'conventional': 'సాంప్రదాయ',
      'mixed': 'మిశ్రమ',
      'other': 'ఇతర',
      'rainfed': 'వర్షాధార',
      'borewell': 'బోరుబావి',
      'canal': 'కాలువ',
      'drip': 'డ్రిప్',
      'sprinkler': 'స్ప్రింక్లర్',
      'edit_profile': 'ప్రొఫైల్‌ను సవరించండి',
      'complete_profile_prompt': 'మీ రైతు ప్రొఫైల్‌ను పూర్తి చేయండి\nRythuMitraను వ్యక్తిగతీకరించడానికి మీ పొలం వివరాలను జోడించండి.',
      'complete_profile': 'ప్రొఫైల్ పూర్తి చేయండి',
      'change_language': 'భాషను మార్చండి',

      'home_greeting': 'నమస్కారం!',
      'home_title': 'రైతుమిత్ర AI',
      'home_subtitle': 'మీ స్మార్ట్ ఫార్మింగ్ అసిస్టెంట్',
      'ask_anything': 'మీ వ్యవసాయం గురించి నన్ను ఏమైనా అడగండి',
      'quick_actions': 'త్వరిత చర్యలు',
      'quick_weather': 'వాతావరణం',
      'quick_prices': 'మార్కెట్ ధరలు',
      'quick_diagnosis': 'పంట వ్యాధి నిర్ధారణ',
      'quick_schemes': 'ప్రభుత్వ పథకాలు',
      'nav_home': 'హోమ్',
      'nav_ai': 'AI అసిస్టెంట్',
      'nav_farm': 'నా వ్యవసాయం',
      'nav_tasks': 'పనులు',
      'nav_more': 'మరిన్ని',
      'ai_thinking': '🤖 రైతుమిత్ర ఆలోచిస్తోంది...',
      'speak_button': 'వినండి',
      'speaking_button': 'మాట్లాడుతోంది...',
      'voice_unavailable': 'ఈ భాషకు వాయిస్ ప్రస్తుతం మీ పరికరంలో అందుబాటులో లేదు.',
      'mic_error': 'మైక్రోఫోన్‌ను ప్రారంభించలేకపోయాము. దయచేసి అనుమతులను తనిఖీ చేయండి.',
      'sug_crop': '🌱 నా పంటకు సమస్య ఉంది',
      'sug_weather': '🌦️ ఈ రోజు వాతావరణం చెప్పండి',
      'sug_water': '💧 నా పంటకు ఎప్పుడు నీరు పెట్టాలి?',
      'sug_price': '📈 మార్కెట్ ధర ఎంత?',
      'ai_greeting': 'నమస్కారం! నేను రైతుమిత్రను.',
      'ai_help': 'మీ వ్యవసాయం గురించి నన్ను ఏమైనా అడగండి.',
      'ai_title': '🤖 రైతుమిత్ర AI అసిస్టెంట్',
      'profile_setup_title': 'ప్రొఫైల్ సెటప్',
      'farmer_profile': 'రైతు ప్రొఫైల్',
      'farm_profile': 'వ్యవసాయ ప్రొఫైల్',
      'farmer_name': 'రైతు పేరు',
      'location': 'ప్రాంతం',
      'farm_name': 'పొలం పేరు (ఐచ్ఛికం)',
      'land_size': 'భూమి పరిమాణం',
      'land_unit': 'యూనిట్',
      'farm_type': 'వ్యవసాయ రకం',
      'current_crops': 'ప్రస్తుత పంటలు',
      'skip_for_now': 'ప్రస్తుతానికి వదిలివేయండి',
      'no_farm_profile': 'మీ వ్యవసాయాన్ని అర్థం చేసుకోవడానికి రైతుమిత్రకు మీ పొలం వివరాలను జోడించండి.',
      'no_crops': 'మీరు ఇంకా పంటలను జోడించలేదు.',
      'memory_title': '🧠 నా పొలం గురించి రైతుమిత్రకు తెలిసినవి',
      'planting_date': 'నాటిన తేదీ',
      'notes': 'గమనికలు',
      'status': 'స్థితి',
      'growing': 'పెరుగుతోంది',
      'needs_attention': 'శ్రద్ధ అవసరం',
      'info_incomplete': 'సమాచారం అసంపూర్ణంగా ఉంది',
      'harvested': 'కోతకోసినవి',
      'ask_rythumitra_crop': '🤖 ఈ పంట గురించి రైతుమిత్రను అడగండి',
      'crop_details': 'పంట వివరాలు',
      'harvested_crops': 'కోతకోసిన పంటలు',
      'seedling': 'మొలక',
      'vegetative': 'పెరుగుదల దశ',
      'fruiting': 'కాయ / గింజ అభివృద్ధి',
      'not_sure': 'ఖచ్చితంగా తెలియదు',
      'add_more_details': 'ఈ పంట గురించి రైతుమిత్రకు బాగా అర్థం కావడానికి మరిన్ని వివరాలను జోడించండి.',
      // Scanner / Vision Feature
      'crop_photo': 'పంట ఫోటో',
      'analyzing_crop': '🔍 రైతుమిత్ర మీ పంటను తనిఖీ చేస్తోంది...',
      'which_crop': 'ఇది ఏ పంట?',
      'select_crop': 'పంటను ఎంచుకోండి',
      'optional_notes': 'అదనపు వివరాలు (ఐచ్ఛికం)',
      'describe_problem': 'ఉదా. ఆకులు పసుపు రంగులోకి మారుతున్నాయి',
      'retake': 'మళ్ళీ తీయండి',
      'analyze': 'విశ్లేషించండి',
      'analysis_result': 'విశ్లేషణ ఫలితం',
      'save_result': 'ఫలితాన్ని దాచండి',
      'stop_audio': 'ఆపు',
      'listen_audio': 'వినండి',
      'ai_uncertainty_warning': 'కేవలం ఫోటో ద్వారా కచ్చితమైన నిర్ధారణ సాధ్యం కాకపోవచ్చు. ఇది కేవలం AI పరిశీలన మాత్రమే.',
      'possible_issues': '⚠️ సంభావ్య కారణాలు',
      'visible_symptoms': '👀 గమనించిన లక్షణాలు',
      'recommended_next_steps': '🌱 తదుపరి చర్యలు',
      'when_to_seek_expert': 'నిపుణుల సహాయం ఎప్పుడు తీసుకోవాలి',
      'take_another_photo': 'మరో ఫోటో తీయండి',
      'scan_crop_problem': 'పంట సమస్యను స్కాన్ చేయండి',
      'take_photo': 'ఫోటో తీయండి',
      'choose_from_gallery': 'గ్యాలరీ నుండి ఎంచుకోండి',
      'scan_this_crop': 'ఈ పంటను స్కాన్ చేయండి',
      'previous_checks': 'గతంలో చేసిన తనిఖీలు',
      'analysis_failed': 'ప్రస్తుతం ఫోటోను విశ్లేషించలేకపోయాము. దయచేసి మళ్ళీ ప్రయత్నించండి.',
      'scan_saved_successfully': 'స్కాన్ ఫలితం విజయవంతంగా సేవ్ చేయబడింది.',
      'crop_health': 'పంట ఆరోగ్యం',
      'check_crop': 'పంటను తనిఖీ చేయండి',
      'crop_analysis': 'పంట విశ్లేషణ',
      'observation': 'పరిశీలన',
      'advice': 'సలహా',
      'precautions': 'జాగ్రత్తలు',
      'no_crop_analysis': 'ప్రస్తుతం ఎలాంటి పంట విశ్లేషణ అందుబాటులో లేదు',
      'crop_analysis_unavailable': 'పంట విశ్లేషణ ప్రస్తుతం అందుబాటులో లేదు',
      'report_history': 'నివేదిక చరిత్ర',
      // Health History
      'crop_health_history': 'పంట ఆరోగ్య చరిత్ర',
      'no_health_checks_yet': 'ఇంకా పంట ఆరోగ్య తనిఖీలు లేవు.\nసమస్య కనిపిస్తే ఫోటో తీయండి.',
      'status_monitoring': 'పరిశీలిస్తున్నాము',
      'status_improved': 'మెరుగుపడింది',
      'status_still_has_problem': 'ఇంకా సమస్య ఉంది',
      'status_not_checked_yet': 'ఇంకా తనిఖీ చేయలేదు',
      'initial_scan': 'మొదటి స్కాన్',
      'timeline': 'టైమ్‌లైన్',
      'no_follow_ups': 'ఇంకా ఫాలో-అప్‌లు లేవు.',
      'farmer_update': 'రైతు అప్‌డేట్',
      'ai_analysis': 'AI విశ్లేషణ',
      'add_follow_up': 'ఫాలో-అప్ జోడించండి',
      'add_note': 'గమనిక జోడించండి',
      'add_photo': 'ఫోటో జోడించండి',
      'analyze_new_photo': 'కొత్త ఫోటోను AI తో విశ్లేషించండి',
      'ask_rythumitra_history': '🤖 ఈ చరిత్ర గురించి రైతుమిత్రను అడగండి',
      'delete_record': 'రికార్డు తొలగించండి',
      'delete_confirm_desc': 'ఈ ఆరోగ్య రికార్డును మరియు దాని ఫాలో-అప్‌లను ఖచ్చితంగా తొలగించాలనుకుంటున్నారా? దీన్ని తిరిగి పొందలేము.',
      // Weather Feature
      'weather_load_error': 'ప్రస్తుతం వాతావరణ సమాచారాన్ని పొందలేకపోయాము.',
      'weather_clear_sky': 'ఆకాశం నిర్మలంగా ఉంది',
      'weather_partly_cloudy': 'కొద్దిగా మేఘావృతం',
      'weather_fog': 'పొగమంచు',
      'weather_drizzle': 'చినుకులు',
      'weather_rain': 'వర్షం',
      'weather_snow': 'మంచు',
      'weather_rain_showers': 'వర్షపు జల్లులు',
      'weather_thunderstorm': 'ఉరుములతో కూడిన వర్షం',
      'weather_cloudy': 'మేఘావృతం',
      'weather_unknown': 'తెలియదు',
      'current_weather': 'ప్రస్తుత వాతావరణం',
      'humidity': 'తేమ',
      'wind': 'గాలి',
      'rain': 'వర్షం',
      'explain_weather_farm': '🤖 నా పొలానికి వాతావరణాన్ని వివరించండి',
      'forecast': 'వాతావరణ సూచన',
      'last_updated': 'చివరిగా అప్‌డేట్ చేయబడినది',
      'today': 'ఈ రోజు',
      'change_location': 'ప్రాంతాన్ని మార్చండి',
      'enter_town_name': 'పట్టణం లేదా జిల్లా పేరు నమోదు చేయండి',
      'getting_weather_info': 'వాతావరణ సమాచారాన్ని పొందుతున్నాము...',
      'retry': 'మళ్ళీ ప్రయత్నించండి',
      // Alerts & Reminders
      'weather_alerts': 'వాతావరణ హెచ్చరికలు',
      'no_alerts': 'ప్రస్తుతం ఎటువంటి హెచ్చరికలు లేవు.',
      'farm_reminders': 'పొలం పనులు (రిమైండర్లు)',
      'add_reminder': 'రిమైండర్ జోడించండి',
      'no_reminders': 'ఎటువంటి రిమైండర్లు లేవు.',
      'enter_title_error': 'దయచేసి పేరు నమోదు చేయండి',
      'reminder_title': 'రిమైండర్ పేరు',
      'date': 'తేదీ',
      'time': 'సమయం',
      'updates': 'అప్‌డేట్‌లు',
      'alert_rain_title': 'ప్రస్తుతం వర్షం',
      'alert_rain_desc': 'మీ ప్రాంతంలో ప్రస్తుతం వర్షం కురుస్తోంది.',
      'alert_temp_title': 'అధిక ఉష్ణోగ్రత',
      'alert_temp_desc': 'ప్రస్తుతం ఉష్ణోగ్రత చాలా ఎక్కువగా ఉంది.',
      'alert_wind_title': 'బలమైన గాలి',
      'alert_wind_desc': 'మీ ప్రాంతంలో బలమైన గాలులు వీస్తున్నాయి.',
      'alert_rain_forecast_title': 'వర్షం సూచన',
      'alert_rain_forecast_desc': 'మీ ప్రాంతంలో త్వరలో వర్షం కురిసే అవకాశం ఉంది.',
      'alert_temp_forecast_title': 'అధిక ఉష్ణోగ్రత సూచన',
      'alert_temp_forecast_desc': 'అధిక ఉష్ణోగ్రత ఉండే అవకాశం ఉంది. వాతావరణ వివరాలు తనిఖీ చేయండి.',
      'alert_temp_change_title': 'ఉష్ణోగ్రత మార్పు',
      'alert_temp_change_desc': 'త్వరలో ఉష్ణోగ్రతలో గణనీయమైన మార్పు ఉంటుంది.',
      'ask_rythumitra': 'రైతుమిత్రను అడగండి',
      // Market Prices
      'market_prices': 'మార్కెట్ ధరలు',
      'market_update': 'మార్కెట్ అప్‌డేట్',
      'view_market': 'మార్కెట్ చూడండి',
      'search_crop': 'పంటను శోధించండి (ఉదా. టమాటా)',
      'data_unavailable': 'మార్కెట్ ధరల సమాచారం అందుబాటులో లేదు.',
      'check_market_price': 'మార్కెట్ ధరను తనిఖీ చేయండి',
      'no_market_price_found': 'మార్కెట్ ధర లభించలేదు',
      'no_market_price_desc': 'ఎంచుకున్న పంట మరియు ప్రాంతానికి మార్కెట్ ధర లభించలేదు.',
      'try_again': 'మళ్లీ ప్రయత్నించండి',
      'search_another_crop': 'మరో పంటను వెతకండి',
      'market_unavailable': 'ప్రస్తుతం మార్కెట్ సమాచారం అందుబాటులో లేదు.',
      'ai_welcome': 'నమస్తే! నేను రైతుమిత్ర AI ని. మీ వ్యవసాయంలో నేను మీకు ఎలా సహాయపడగలను?',
      'sug_my_crop': '🌱 నా పంట',
      'sug_weather_quick': '🌦️ వాతావరణం',
      'sug_market_price': '💰 మార్కెట్ ధర',
      'sug_crop_problem': '🐛 పంట సమస్య',
      'sug_irrigation': '💧 నీటిపారుదల',
      'sug_farming_advice': '🌾 వ్యవసాయ సలహా',
      'ask_placeholder': 'రైతుమిత్రను అడగండి...',
      'send': 'పంపండి',
      'clear_chat': '🗑️ చాట్ క్లియర్ చేయండి',
      'clear_chat_confirm': 'ఈ సంభాషణను క్లియర్ చేయాలా?',
      'clear': 'క్లియర్ చేయండి',
      'ai_unavailable': 'రైతుమిత్ర AI తాత్కాలికంగా అందుబాటులో లేదు. దయచేసి మళ్లీ ప్రయత్నించండి.',
      'ai_conn_unavailable': '🔴 AI కనెక్షన్ అందుబాటులో లేదు',
      'farm_location': 'పొలం ప్రాంతం',
      'add_farm_location_weather': 'స్థానిక వాతావరణాన్ని చూడటానికి మీ పొలం ప్రాంతాన్ని జోడించండి.',
      'go_to_farm_location': 'పొలం ప్రాంతానికి వెళ్లండి',
      'weather_unavailable': 'ప్రస్తుతం వాతావరణ సమాచారం అందుబాటులో లేదు.',
      'offline_weather_warning': 'గతంలో భద్రపరిచిన డేటాను చూపుతున్నాము. మీరు ఆఫ్‌లైన్‌లో ఉన్నారు.',
      'no_crops_yet': 'ఇంకా పంటలు జోడించబడలేదు.',
      'add_crop_market': 'పంటను జోడించండి',
      'getting_market_info': 'మార్కెట్ సమాచారాన్ని పొందుతున్నాము...',
      'offline_market_warning': 'మార్కెట్ సమాచారం ప్రస్తుతం అందుబాటులో లేదు.',
      'no_market_data': 'ప్రస్తుతం మార్కెట్ డేటా అందుబాటులో లేదు.',
      'minimum_price': 'కనిష్ట ధర',
      'maximum_price': 'గరిష్ట ధర',
      'modal_price': 'మోడల్ ధర',
      'reported_on': 'నివేదించిన తేదీ:',
      'unit_label': 'యూనిట్:',
      // Farm Expenses
      'farm_expenses': 'పొలం ఖర్చులు',
      'total_expenses': 'మొత్తం ఖర్చులు',
      'expense_history': 'ఖర్చుల చరిత్ర',
      'add_expense': 'ఖర్చును జోడించండి',
      'expense_type': 'ఖర్చు రకం',
      'amount': 'మొత్తం',
      'seeds': 'విత్తనాలు',
      'fertilizer': 'ఎరువు',
      'pesticides': 'పురుగుల మందులు',
      'labour': 'కూలీ',
      'machinery': 'యంత్రాలు',
      'transport': 'రవాణా',
      'electricity': 'విద్యుత్',
      'general_farm_expense': 'సాధారణ పొలం ఖర్చు',
      'no_expenses_recorded_yet': 'ఇంకా ఎలాంటి ఖర్చులు నమోదు చేయబడలేదు',
      'add_your_farm_expenses': 'మీ ఖర్చులను ట్రాక్ చేయడానికి పొలం ఖర్చులను జోడించండి.',
      'delete_expense_confirm': 'మీరు ఈ ఖర్చును తొలగించాలనుకుంటున్నారా?',
      'all': 'అన్ని',
      'invalid_amount': 'చెల్లని మొత్తం',
      'expense_other': 'ఇతర',
      'save_action': 'సేవ్ చేయండి',
      'cancel_action': 'రద్దు చేయండి',
      'edit_action': 'సవరించండి',
      'delete_action': 'తొలగించండి',
      // Farm Income
      'farm_income': 'పొలం ఆదాయం',
      'sales': 'అమ్మకాలు',
      'total_income': 'మొత్తం ఆదాయం',
      'sales_history': 'అమ్మకాల చరిత్ర',
      'add_sale': 'అమ్మకాన్ని జోడించండి',
      'quantity': 'పరిమాణం',
      'quantity_unit': 'పరిమాణం యూనిట్',
      'selling_price': 'అమ్మకపు ధర',
      'price_unit': 'ధర యూనిట్',
      'buyer': 'కొనుగోలుదారు',
      'market_name': 'మార్కెట్',
      'sale_date': 'అమ్మకం తేదీ',
      'kg': 'కిలో (Kg)',
      'quintal': 'క్వింటాల్ (Quintal)',
      'ton': 'టన్ను (Ton)',
      'rs_per_kg': '₹ / కిలో',
      'rs_per_quintal': '₹ / క్వింటాల్',
      'rs_per_ton': '₹ / టన్ను',
      'total_sale_value': 'మొత్తం అమ్మకపు విలువ',
      'no_sales_recorded_yet': 'ఇంకా ఎలాంటి అమ్మకాలు నమోదు చేయబడలేదు',
      'record_your_crop_sales': 'మీ పొలం ఆదాయాన్ని ట్రాక్ చేయడానికి మీ పంట అమ్మకాలను రికార్డ్ చేయండి.',
      'delete_sale_confirm': 'మీరు ఈ అమ్మకాన్ని తొలగించాలనుకుంటున్నారా?',
      // Farm Financial Summary
      'farm_financial_summary': 'పొలం ఆర్థిక సారాంశం',
      'net_balance': 'నికర నిల్వ',
      'crop_summary': 'పంట సారాంశం',
      'all_time': 'మొత్తం సమయం',
      'this_month': 'ఈ నెల',
      'custom_date_range': 'కస్టమ్ తేదీ పరిధి',
      'no_financial_records_yet': 'ఇంకా ఎలాంటి ఆర్థిక రికార్డులు లేవు',
      'add_income_expenses_prompt': 'మీ పొలం సారాంశాన్ని చూడటానికి మీ పొలం ఆదాయం మరియు ఖర్చులను జోడించండి',
      'add_income': 'ఆదాయాన్ని జోడించండి',
      'select_date_range': 'తేదీ పరిధిని ఎంచుకోండి',
      'from_date': 'నుండి',
      'to_date': 'వరకు',
      // Farm Calendar
      'farm_calendar': 'పొలం క్యాలెండర్',
      'previous_month': 'మునుపటి నెల',
      'next_month': 'తర్వాతి నెల',
      'selected_date': 'ఎంచుకున్న తేదీ',
      'no_farm_activities_for_this_date': 'ఈ తేదీన ఎలాంటి పొలం కార్యకలాపాలు లేవు',
      'event_details': 'ఈవెంట్ వివరాలు',
      'event_type_reminder': 'రిమైండర్',
      'event_type_activity': 'కార్యకలాపం',
      'event_type_growth': 'పంట పెరుగుదల',
      'event_type_photo': 'పంట ఫోటో',
      // Backup & Restore
      'backup_restore': 'డేటా బ్యాకప్ & రీస్టోర్',
      'create_backup': 'బ్యాకప్ సృష్టించు',
      'restore_backup': 'బ్యాకప్ రీస్టోర్ చేయి',
      'backup_success': 'బ్యాకప్ విజయవంతంగా సృష్టించబడింది',
      'restore_farm_data': 'మీ వ్యవసాయ డేటాను రీస్టోర్ చేయండి',
      'restoring_data': 'మీ వ్యవసాయ డేటాను రీస్టోర్ చేస్తోంది...',
      'invalid_backup_file': 'చెల్లని బ్యాకప్ ఫైల్',
      'continue_btn': 'కొనసాగించు',
      'backup_version': 'బ్యాకప్ వెర్షన్',
      'backup_date': 'బ్యాకప్ తేదీ',
      'backup_warning': 'ఈ బ్యాకప్ మీ ప్రస్తుత వ్యవసాయ డేటాను భర్తీ చేయవచ్చు',
      'backup_not_supported': 'ఈ బ్యాకప్ RythuMitra కొత్త వెర్షన్ ఉపయోగించి సృష్టించబడింది.',
      'restore_success': 'మీ వ్యవసాయ డేటా విజయవంతంగా రీస్టోర్ చేయబడింది.',
      'backup_photos_not_included': 'గమనిక: పంట ఫోటోలు బ్యాకప్‌లో చేర్చబడలేదు.',
      // Emergency Help
      'emergency_help': 'అత్యవసర సహాయం',
      'important_contacts': 'ముఖ్యమైన పరిచయాలు',
      'add_contact': 'పరిచయాన్ని జోడించండి',
      'contact_name': 'పరిచయం పేరు',
      'phone_number': 'ఫోన్ నంబర్',
      'contact_category': 'వర్గం',
      'contact_notes': 'గమనికలు',
      'call_btn': 'కాల్ చేయండి',
      'edit_btn': 'సవరించు',
      'delete_btn': 'తొలగించు',
      'cancel_btn': 'రద్దు చేయి',
      'quick_access': 'శీఘ్ర ప్రాప్యత',
      'no_contacts_yet': 'ఇంకా ముఖ్యమైన పరిచయాలు జోడించబడలేదు.',
      'delete_contact_confirm': 'మీరు ఈ పరిచయాన్ని తొలగించాలనుకుంటున్నారా?',
      'cat_agriculture_officer': 'వ్యవసాయ అధికారి',
      'cat_veterinary_help': 'వెటర్నరీ సహాయం',
      'cat_family': 'కుటుంబం',
      'cat_friend': 'స్నేహితుడు',
      'cat_medical_help': 'వైద్య సహాయం',
      'cat_emergency': 'అత్యవసర',
      'cat_other': 'ఇతర',
      // Daily Farm Planner
      'planner_title': 'రోజువారీ వ్యవసాయ ప్రణాళిక',
      'planner_todays_tasks': 'నేటి పనులు',
      'planner_upcoming_tasks': 'రాబోయే పనులు',
      'planner_completed_tasks': 'పూర్తయిన పనులు',
      'planner_add_task': 'పనిని జోడించండి',
      'planner_task_title': 'పని పేరు',
      'planner_select_date': 'తేదీని ఎంచుకోండి',
      'planner_select_time': 'సమయాన్ని ఎంచుకోండి',
      'planner_related_crop': 'సంబంధిత పంట',
      'planner_notes': 'గమనికలు',
      'planner_completed': 'పూర్తయింది',
      'planner_pending': 'పెండింగ్',
      'planner_overdue': 'గడువు ముగిసింది',
      'planner_delete_task': 'పనిని తొలగించండి',
      'planner_delete_confirm': 'మీరు ఈ పనిని తొలగించాలనుకుంటున్నారా?',
      'planner_daily_progress': 'రోజువారీ పురోగతి',
      'planner_total_tasks': 'మొత్తం పనులు',
      'planner_remaining': 'మిగిలినవి',
      'planner_today': 'ఈ రోజు',
      'planner_tomorrow': 'రేపు',
      'planner_this_week': 'ఈ వారం',
      'planner_all_tasks': 'అన్ని పనులు',
      'crop_dashboard': 'పంట డాష్‌బోర్డ్',
      'net_crop_balance': 'నికర పంట బ్యాలెన్స్',
      'dashboard_summary': 'డాష్‌బోర్డ్ సారాంశం',
      'dashboard_records': 'రికార్డులు',
      'dashboard_activities': 'కార్యకలాపాలు',
      'dashboard_tasks': 'పనులు',
      'dashboard_reminders': 'రిమైండర్‌లు',
      'dashboard_expenses': 'ఖర్చులు',
      'dashboard_income': 'ఆదాయం',
      'dashboard_photos': 'ఫోటోలు',
    },
    'hi': {
      'farm_activity': 'खेत की गतिविधि',
      'farm_activity_log': 'खेत की गतिविधि लॉग',
      'activity_history': 'गतिविधि इतिहास',
      'add_activity': 'गतिविधि जोड़ें',
      'activity_type': 'गतिविधि का प्रकार',
      'general_farm_activity': 'सामान्य खेत गतिविधि',
      'delete_activity_confirm': 'क्या आप इस गतिविधि को हटाना चाहते हैं?',
      'no_farm_activities_yet': '📋 अभी तक कोई खेत गतिविधि नहीं',
      'record_farm_activities_prompt': 'एक सरल इतिहास रखने के लिए अपनी खेत गतिविधियों को रिकॉर्ड करें।',
      'irrigation': 'सिंचाई',
      'fertilizer_application': 'उर्वरक आवेदन',
      'pest_control': 'कीट नियंत्रण',
      'weed_control': 'खरपतवार नियंत्रण',
      'spraying': 'छिड़काव',
      'field_inspection': 'खेत का निरीक्षण',
      'harvesting': 'कटाई',
      'selling': 'बेचना',
      'growth_tracking': 'फसल विकास ट्रैकिंग',
      'add_growth_update': 'विकास अद्यतन जोड़ें',
      'growth_stage': 'विकास चरण',
      'no_growth_updates_yet': '🌱 अभी तक कोई विकास अपडेट नहीं',
      'add_an_update_to_keep_track': 'अपनी फसल के विकास को ट्रैक करने के लिए एक अपडेट जोड़ें।',
      'seed_sowing': 'बीज / बुवाई',
      'germination': 'अंकुरण',
      'vegetative_growth': 'वानस्पतिक विकास',
      'flowering': 'फूल आना',
      'fruit_grain_development': 'फल / अनाज विकास',
      'maturity': 'परिपक्वता',
      'harvest_ready': 'कटाई के लिए तैयार',
      'delete_update_confirm': 'क्या आप इस विकास अद्यतन को हटाना चाहते हैं?',
      'general_farm_reminder': 'सामान्य कृषि अनुस्मारक',
      'delete_reminder_confirm': 'क्या आप इस अनुस्मारक को हटाना चाहते हैं?',
      'upcoming': 'आगामी',
      'overdue': 'अतिदेय',
      'completed': 'पूरा हुआ',
      'mark_as_completed': 'पूर्ण के रूप में चिह्नित करें',
      'delete': 'हटाएं',
      'add_time': 'समय जोड़ें',
      'clear_time': 'समय हटाएं',
      'no_reminders_yet': '🔔 अभी तक कोई अनुस्मारक नहीं',
      'create_a_reminder': 'अपनी कृषि गतिविधियों के लिए एक अनुस्मारक बनाएं।',
      'variety': 'किस्म',
      'sowing_date': 'बुवाई की तारीख',
      'expected_harvest_date': 'संभावित कटाई की तारीख',
      'farm_area': 'खेत का क्षेत्रफल',
      'no_crops_added_yet': '🌱 अभी तक कोई फसल नहीं जोड़ी गई',
      'add_your_crops': 'अपनी कृषि जानकारी को व्यवस्थित रखने के लिए अपनी फसलें जोड़ें।',
      'remove_crop_confirm': 'क्या आप इस फसल को हटाना चाहते हैं?',
      'add_crop': '+ फसल जोड़ें',
      'edit_crop': '✏️ फसल संपादित करें',
      'crop_name': 'फसल का नाम',
      'save': 'सहेजें',
      'cancel': 'रद्द करें',
      'remove': '🗑️ हटाएं',
      'edit': '✏️ संपादित करें',
      'use_current_location': '📍 वर्तमान स्थान का उपयोग करें',
      'location_unavailable': 'स्थान अनुपलब्ध है',
      'location_saved': 'स्थान सहेजा गया',
      'location_updated': 'स्थान अपडेट किया गया',
      'location_permission_denied': 'स्थान की अनुमति अस्वीकार कर दी गई। कृपया मैन्युअल रूप से दर्ज करें।',

      'village': 'गाँव',
      'district': 'ज़िला',
      'state': 'राज्य',
      'my_crops': 'मेरी फसलें',
      'remove_crop': 'हटाएं',
      'acres': 'एकड़',
      'hectares': 'हेक्टेयर',
      'irrigation_type': 'सिंचाई का प्रकार',
      'farming_type': 'खेती का प्रकार',
      'organic': 'जैविक',
      'conventional': 'पारंपरिक',
      'mixed': 'मिश्रित',
      'other': 'अन्य',
      'rainfed': 'वर्षा आधारित',
      'borewell': 'बोरवेल',
      'canal': 'नहर',
      'drip': 'ड्रिप',
      'sprinkler': 'स्प्रिंकलर',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'complete_profile_prompt': 'अपना किसान प्रोफ़ाइल पूरा करें\nRythuMitra को निजीकृत करने के लिए अपने खेत के विवरण जोड़ें।',
      'complete_profile': 'प्रोफ़ाइल पूरी करें',
      'change_language': 'भाषा बदलें',

      'home_greeting': 'नमस्ते!',
      'home_title': 'रायथुमित्रा AI',
      'home_subtitle': 'आपका स्मार्ट फार्मिंग सहायक',
      'ask_anything': 'मुझसे अपनी खेती के बारे में कुछ भी पूछें',
      'quick_actions': 'त्वरित कार्रवाई',
      'quick_weather': 'मौसम',
      'quick_prices': 'बाजार भाव',
      'quick_diagnosis': 'फसल निदान',
      'quick_schemes': 'सरकारी योजनाएं',
      'nav_home': 'होम',
      'nav_ai': 'AI सहायक',
      'nav_farm': 'मेरा खेत',
      'nav_tasks': 'कार्य',
      'nav_more': 'अधिक',
      'ai_thinking': '🤖 रायथुमित्रा सोच रहा है...',
      'speak_button': 'सुनें',
      'speaking_button': 'बोल रहा है...',
      'voice_unavailable': 'आपके उपकरण पर इस भाषा के लिए आवाज़ वर्तमान में उपलब्ध नहीं है।',
      'mic_error': 'माइक्रोफ़ोन प्रारंभ नहीं हो सका। कृपया अनुमतियों की जांच करें।',
      'sug_crop': '🌱 मेरी फसल में कोई समस्या है',
      'sug_weather': '🌦️ मुझे आज का मौसम बताएं',
      'sug_water': '💧 मुझे अपनी फसल को पानी कब देना चाहिए?',
      'sug_price': '📈 बाजार मूल्य क्या है?',
      'ai_greeting': 'नमस्ते! मैं रायथुमित्रा हूँ।',
      'ai_help': 'आप मुझसे अपनी खेती के बारे में कुछ भी पूछ सकते हैं।',
      'ai_title': '🤖 रायथुमित्रा AI सहायक',
      'profile_setup_title': 'प्रोफ़ाइल सेटअप',
      'farmer_profile': 'किसान प्रोफ़ाइल',
      'farm_profile': 'खेत प्रोफ़ाइल',
      'farmer_name': 'किसान का नाम',
      'location': 'स्थान',
      'farm_name': 'खेत का नाम (वैकल्पिक)',
      'land_size': 'भूमि का आकार',
      'land_unit': 'इकाई',
      'farm_type': 'खेत का प्रकार',
      'current_crops': 'वर्तमान फसलें',
      'skip_for_now': 'अभी के लिए छोड़ दें',
      'no_farm_profile': 'रायथुमित्रा को आपकी खेती समझने में मदद करने के लिए अपने खेत का विवरण जोड़ें।',
      'no_crops': 'आपने अभी तक कोई फसल नहीं जोड़ी है।',
      'memory_title': '🧠 रायथुमित्रा मेरे खेत के बारे में क्या जानता है',
      'planting_date': 'बुवाई की तारीख',
      'notes': 'टिप्पणियाँ',
      'status': 'स्थिति',
      'growing': 'बढ़ रहा है',
      'needs_attention': 'ध्यान देने की आवश्यकता है',
      'info_incomplete': 'जानकारी अधूरी है',
      'harvested': 'काटा हुआ',
      'ask_rythumitra_crop': '🤖 रायथुमित्रा से इस फसल के बारे में पूछें',
      'crop_details': 'फसल का विवरण',
      'harvested_crops': 'काटी गई फसलें',
      'seedling': 'अंकुर',
      'vegetative': 'वानस्पतिक',
      'fruiting': 'फल / अनाज विकास',
      'not_sure': 'पक्का नहीं',
      'add_more_details': 'रायथुमित्रा को इस फसल को बेहतर ढंग से समझने में मदद करने के लिए और विवरण जोड़ें।',
      // Scanner / Vision Feature
      'crop_photo': 'फसल की फोटो',
      'analyzing_crop': '🔍 ऋतुमित्र आपकी फसल की जाँच कर रहा है...',
      'which_crop': 'यह कौन सी फसल है?',
      'select_crop': 'फसल चुनें',
      'optional_notes': 'अतिरिक्त विवरण (वैकल्पिक)',
      'describe_problem': 'उदा. पत्ते पीले हो रहे हैं',
      'retake': 'फिर से लें',
      'analyze': 'विश्लेषण करें',
      'analysis_result': 'विश्लेषण परिणाम',
      'save_result': 'परिणाम सहेजें',
      'stop_audio': 'रोकें',
      'listen_audio': 'सुनें',
      'ai_uncertainty_warning': 'केवल फोटो से सटीक निदान संभव नहीं हो सकता है। यह सिर्फ एक एआई अवलोकन है।',
      'possible_issues': '⚠️ संभावित कारण',
      'visible_symptoms': '👀 क्या देखा गया',
      'recommended_next_steps': '🌱 आप क्या जाँच सकते हैं',
      'when_to_seek_expert': 'विशेषज्ञ की मदद कब लें',
      'take_another_photo': 'एक और फोटो लें',
      'scan_crop_problem': 'फसल की समस्या को स्कैन करें',
      'take_photo': 'फोटो लें',
      'choose_from_gallery': 'गैलरी से चुनें',
      'scan_this_crop': 'इस फसल को स्कैन करें',
      'previous_checks': 'पिछली जाँच',
      'analysis_failed': 'अभी फसल की तस्वीर का विश्लेषण नहीं कर पा रहे हैं। कृपया पुनः प्रयास करें।',
      'scan_saved_successfully': 'स्कैन परिणाम सफलतापूर्वक सहेजा गया।',
      'crop_health': 'फसल स्वास्थ्य',
      'check_crop': 'फसल की जाँच करें',
      'crop_analysis': 'फसल विश्लेषण',
      'observation': 'अवलोकन',
      'advice': 'सलाह',
      'precautions': 'सावधानियां',
      'no_crop_analysis': 'अभी कोई फसल विश्लेषण उपलब्ध नहीं है',
      'crop_analysis_unavailable': 'फसल विश्लेषण वर्तमान में अनुपलब्ध है',
      'report_history': 'रिपोर्ट इतिहास',
      // Health History
      'crop_health_history': 'फसल का स्वास्थ्य इतिहास',
      'no_health_checks_yet': 'अभी तक कोई फसल स्वास्थ्य जांच नहीं हुई है।\nयदि कोई समस्या दिखे तो फोटो लें।',
      'status_monitoring': 'निगरानी कर रहे हैं',
      'status_improved': 'सुधार हुआ',
      'status_still_has_problem': 'अभी भी समस्या है',
      'status_not_checked_yet': 'अभी जांच नहीं हुई है',
      'initial_scan': 'प्रारंभिक स्कैन',
      'timeline': 'समयरेखा',
      'no_follow_ups': 'अभी तक कोई फॉलो-अप नहीं।',
      'farmer_update': 'किसान अपडेट',
      'ai_analysis': 'एआई विश्लेषण',
      'add_follow_up': 'फॉलो-अप जोड़ें',
      'add_note': 'नोट जोड़ें',
      'add_photo': 'फोटो जोड़ें',
      'analyze_new_photo': 'एआई के साथ नई फोटो का विश्लेषण करें',
      'ask_rythumitra_history': '🤖 इस इतिहास के बारे में रायथुमित्रा से पूछें',
      'delete_record': 'रिकॉर्ड हटाएं',
      'delete_confirm_desc': 'क्या आप वाकई इस स्वास्थ्य रिकॉर्ड और इसके सभी फॉलो-अप को हटाना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती।',
      // Weather Feature
      'weather_load_error': 'अभी मौसम की जानकारी नहीं मिल पा रही है।',
      'weather_clear_sky': 'आसमान साफ है',
      'weather_partly_cloudy': 'आंशिक रूप से बादल छाए रहेंगे',
      'weather_fog': 'कोहरा',
      'weather_drizzle': 'बूंदाबांदी',
      'weather_rain': 'बारिश',
      'weather_snow': 'बर्फ',
      'weather_rain_showers': 'बारिश की बौछारें',
      'weather_thunderstorm': 'आंधी तूफान',
      'weather_cloudy': 'बादल',
      'weather_unknown': 'अज्ञात',
      'current_weather': 'वर्तमान मौसम',
      'humidity': 'नमी',
      'wind': 'हवा',
      'rain': 'बारिश',
      'explain_weather_farm': '🤖 मेरे खेत के लिए मौसम समझाएं',
      'forecast': 'मौसम का पूर्वानुमान',
      'last_updated': 'अंतिम अपडेट',
      'today': 'आज',
      'change_location': 'स्थान बदलें',
      'enter_town_name': 'कस्बे या जिले का नाम दर्ज करें',
      'getting_weather_info': 'मौसम की जानकारी प्राप्त की जा रही है...',
      'retry': 'पुनः प्रयास करें',
      // Alerts & Reminders
      'weather_alerts': 'मौसम अलर्ट',
      'no_alerts': 'अभी कोई महत्वपूर्ण अलर्ट नहीं है।',
      'farm_reminders': 'खेत के रिमाइंडर',
      'add_reminder': 'रिमाइंडर जोड़ें',
      'no_reminders': 'कोई रिमाइंडर सेट नहीं है।',
      'enter_title_error': 'कृपया शीर्षक दर्ज करें',
      'reminder_title': 'रिमाइंडर का शीर्षक',
      'date': 'तारीख',
      'time': 'समय',
      'updates': 'अपडेट',
      'alert_rain_title': 'अभी बारिश',
      'alert_rain_desc': 'आपके क्षेत्र में अभी बारिश हो रही है।',
      'alert_temp_title': 'उच्च तापमान',
      'alert_temp_desc': 'तापमान वर्तमान में बहुत अधिक है।',
      'alert_wind_title': 'तेज़ हवा',
      'alert_wind_desc': 'आपके क्षेत्र में तेज़ हवाएँ चल रही हैं।',
      'alert_rain_forecast_title': 'बारिश की उम्मीद',
      'alert_rain_forecast_desc': 'आपके क्षेत्र में जल्द ही बारिश की उम्मीद है।',
      'alert_temp_forecast_title': 'उच्च तापमान की उम्मीद',
      'alert_temp_forecast_desc': 'उच्च तापमान की उम्मीद है। अपने खेत के लिए मौसम विवरण देखें।',
      'alert_temp_change_title': 'तापमान परिवर्तन',
      'alert_temp_change_desc': 'जल्द ही महत्वपूर्ण तापमान परिवर्तन की उम्मीद है।',
      'ask_rythumitra': 'रायथुमित्रा से पूछें',
      // Market Prices
      'market_prices': 'बाजार भाव',
      'market_update': 'बाजार अपडेट',
      'view_market': 'बाजार देखें',
      'search_crop': 'फसल खोजें (उदा. टमाटर)',
      'data_unavailable': 'बाजार भाव की जानकारी उपलब्ध नहीं है।',
      'check_market_price': 'बाजार भाव जांचें',
      'no_market_price_found': 'कोई बाजार भाव नहीं मिला',
      'no_market_price_desc': 'इस फसल और चयनित स्थान के लिए कोई बाजार भाव नहीं मिला।',
      'try_again': 'पुनः प्रयास करें',
      'search_another_crop': 'दूसरी फसल खोजें',
      'market_unavailable': 'बाजार की जानकारी अस्थायी रूप से अनुपलब्ध है।',
      'ai_welcome': 'नमस्ते! मैं रायथुमित्रा AI हूँ। मैं आपके खेत के लिए आपकी कैसे मदद कर सकता हूँ?',
      'sug_my_crop': '🌱 मेरी फसल',
      'sug_weather_quick': '🌦️ मौसम',
      'sug_market_price': '💰 बाजार मूल्य',
      'sug_crop_problem': '🐛 फसल की समस्या',
      'sug_irrigation': '💧 सिंचाई',
      'sug_farming_advice': '🌾 खेती की सलाह',
      'ask_placeholder': 'रायथुमित्रा से पूछें...',
      'send': 'भेजें',
      'clear_chat': '🗑️ चैट साफ़ करें',
      'clear_chat_confirm': 'क्या आप इस बातचीत को साफ़ करना चाहते हैं?',
      'clear': 'साफ़ करें',
      'ai_unavailable': 'रायथुमित्रा AI अस्थायी रूप से अनुपलब्ध है। कृपया पुनः प्रयास करें।',
      'ai_conn_unavailable': '🔴 AI कनेक्शन अनुपलब्ध',
      'farm_location': 'खेत का स्थान',
      'add_farm_location_weather': 'स्थानीय मौसम देखने के लिए अपने खेत का स्थान जोड़ें।',
      'go_to_farm_location': 'खेत के स्थान पर जाएं',
      'weather_unavailable': 'मौसम की जानकारी वर्तमान में अनुपलब्ध है।',
      'offline_weather_warning': 'पहले से सहेजा गया डेटा दिखाया जा रहा है। आप ऑफ़लाइन हैं।',
      'no_crops_yet': 'अभी तक कोई फसल नहीं जोड़ी गई है।',
      'add_crop_market': 'फसल जोड़ें',
      'getting_market_info': 'बाजार की जानकारी प्राप्त की जा रही है...',
      'offline_market_warning': 'बाजार की जानकारी वर्तमान में अनुपलब्ध है।',
      'no_market_data': 'अभी कोई बाजार डेटा उपलब्ध नहीं है।',
      'minimum_price': 'न्यूनतम मूल्य',
      'maximum_price': 'अधिकतम मूल्य',
      'modal_price': 'मॉडल मूल्य',
      'reported_on': 'रिपोर्ट की गई तिथि:',
      'unit_label': 'इकाई:',
      // Farm Expenses
      'farm_expenses': 'खेत के खर्च',
      'total_expenses': 'कुल खर्च',
      'expense_history': 'खर्च का इतिहास',
      'add_expense': 'खर्च जोड़ें',
      'expense_type': 'खर्च का प्रकार',
      'amount': 'रकम',
      'seeds': 'बीज',
      'fertilizer': 'उर्वरक',
      'pesticides': 'कीटनाशक',
      'labour': 'मज़दूरी',
      'machinery': 'मशीनरी',
      'transport': 'परिवहन',
      'electricity': 'बिजली',
      'general_farm_expense': 'सामान्य खेत का खर्च',
      'no_expenses_recorded_yet': 'अभी तक कोई खर्च दर्ज नहीं किया गया है',
      'add_your_farm_expenses': 'अपने खर्च पर नज़र रखने के लिए अपने खेत के खर्च जोड़ें।',
      'delete_expense_confirm': 'क्या आप इस खर्च को हटाना चाहते हैं?',
      'all': 'सभी',
      'invalid_amount': 'अमान्य राशि',
      'expense_other': 'अन्य',
      'save_action': 'सहेजें',
      'cancel_action': 'रद्द करें',
      'edit_action': 'संपादित करें',
      'delete_action': 'हटाएं',
      // Farm Income
      'farm_income': 'खेत की आय',
      'sales': 'बिक्री',
      'total_income': 'कुल आय',
      'sales_history': 'बिक्री का इतिहास',
      'add_sale': 'बिक्री जोड़ें',
      'quantity': 'मात्रा',
      'quantity_unit': 'मात्रा की इकाई',
      'selling_price': 'बिक्री मूल्य',
      'price_unit': 'मूल्य की इकाई',
      'buyer': 'ख़रीदार',
      'market_name': 'बाज़ार',
      'sale_date': 'बिक्री की तारीख',
      'kg': 'किलो (Kg)',
      'quintal': 'क्विंटल (Quintal)',
      'ton': 'टन (Ton)',
      'rs_per_kg': '₹ / किलो',
      'rs_per_quintal': '₹ / क्विंटल',
      'rs_per_ton': '₹ / टन',
      'total_sale_value': 'कुल बिक्री मूल्य',
      'no_sales_recorded_yet': 'अभी तक कोई बिक्री दर्ज नहीं की गई है',
      'record_your_crop_sales': 'अपनी खेत की आय पर नज़र रखने के लिए अपनी फसल की बिक्री रिकॉर्ड करें।',
      'delete_sale_confirm': 'क्या आप इस बिक्री को हटाना चाहते हैं?',
      // Farm Financial Summary
      'farm_financial_summary': 'खेत का वित्तीय सारांश',
      'net_balance': 'शुद्ध शेष',
      'crop_summary': 'फसल का सारांश',
      'all_time': 'हर समय',
      'this_month': 'इस महीने',
      'custom_date_range': 'कस्टम दिनांक सीमा',
      'no_financial_records_yet': 'अभी तक कोई वित्तीय रिकॉर्ड नहीं है',
      'add_income_expenses_prompt': 'अपने खेत का सारांश देखने के लिए अपनी खेत की आय और व्यय जोड़ें',
      'add_income': 'आय जोड़ें',
      'select_date_range': 'दिनांक सीमा चुनें',
      'from_date': 'से',
      'to_date': 'तक',
      // Farm Calendar
      'farm_calendar': 'खेत का कैलेंडर',
      'previous_month': 'पिछला महीना',
      'next_month': 'अगला महीना',
      'selected_date': 'चयनित तिथि',
      'no_farm_activities_for_this_date': 'इस तिथि के लिए कोई खेत गतिविधि नहीं है',
      'event_details': 'इवेंट का विवरण',
      'event_type_reminder': 'रिमाइंडर',
      'event_type_activity': 'गतिविधि',
      'event_type_growth': 'फसल की वृद्धि',
      'event_type_photo': 'फसल की फोटो',
      // Backup & Restore
      'backup_restore': 'डेटा बैकअप और रीस्टोर',
      'create_backup': 'बैकअप बनाएँ',
      'restore_backup': 'बैकअप रीस्टोर करें',
      'backup_success': 'बैकअप सफलतापूर्वक बनाया गया',
      'restore_farm_data': 'अपना फार्म डेटा रीस्टोर करें',
      'restoring_data': 'आपका फार्म डेटा रीस्टोर किया जा रहा है...',
      'invalid_backup_file': 'अमान्य बैकअप फ़ाइल',
      'continue_btn': 'जारी रखें',
      'backup_version': 'बैकअप संस्करण',
      'backup_date': 'बैकअप दिनांक',
      'backup_warning': 'यह बैकअप आपके वर्तमान फार्म डेटा को बदल सकता है',
      'backup_not_supported': 'यह बैकअप RythuMitra के नए संस्करण का उपयोग करके बनाया गया था।',
      'restore_success': 'आपका फार्म डेटा सफलतापूर्वक रीस्टोर किया गया।',
      'backup_photos_not_included': 'नोट: फसल तस्वीरें बैकअप में शामिल नहीं हैं।',
      // Emergency Help
      'emergency_help': 'आपातकालीन सहायता',
      'important_contacts': 'महत्वपूर्ण संपर्क',
      'add_contact': 'संपर्क जोड़ें',
      'contact_name': 'संपर्क नाम',
      'phone_number': 'फ़ोन नंबर',
      'contact_category': 'श्रेणी',
      'contact_notes': 'टिप्पणियाँ',
      'call_btn': 'कॉल करें',
      'edit_btn': 'संपादित करें',
      'delete_btn': 'हटाएं',
      'cancel_btn': 'रद्द करें',
      'quick_access': 'त्वरित पहुँच',
      'no_contacts_yet': 'अभी तक कोई महत्वपूर्ण संपर्क नहीं जोड़ा गया।',
      'delete_contact_confirm': 'क्या आप इस संपर्क को हटाना चाहते हैं?',
      'cat_agriculture_officer': 'कृषि अधिकारी',
      'cat_veterinary_help': 'पशु चिकित्सा सहायता',
      'cat_family': 'परिवार',
      'cat_friend': 'दोस्त',
      'cat_medical_help': 'चिकित्सा सहायता',
      'cat_emergency': 'आपातकालीन',
      'cat_other': 'अन्य',
    },
    'ta': {
      'farm_activity': 'பண்ணை செயல்பாடு',
      'farm_activity_log': 'பண்ணை செயல்பாடு பதிவு',
      'activity_history': 'செயல்பாட்டு வரலாறு',
      'add_activity': 'செயல்பாட்டைச் சேர்',
      'activity_type': 'செயல்பாட்டு வகை',
      'general_farm_activity': 'பொது பண்ணை செயல்பாடு',
      'delete_activity_confirm': 'இந்த செயல்பாட்டை நீக்க விரும்புகிறீர்களா?',
      'no_farm_activities_yet': '📋 இன்னும் பண்ணை செயல்பாடுகள் இல்லை',
      'record_farm_activities_prompt': 'எளிமையான வரலாற்றை வைத்திருக்க உங்கள் பண்ணை செயல்பாடுகளைப் பதிவு செய்யவும்.',
      'irrigation': 'நீர்ப்பாசனம்',
      'fertilizer_application': 'உர பயன்பாடு',
      'pest_control': 'பூச்சி கட்டுப்பாடு',
      'weed_control': 'களை கட்டுப்பாடு',
      'spraying': 'தெளித்தல்',
      'field_inspection': 'கள ஆய்வு',
      'harvesting': 'அறுவடை',
      'selling': 'விற்பனை',
      'growth_tracking': 'பயிர் வளர்ச்சி கண்காணிப்பு',
      'add_growth_update': 'வளர்ச்சி புதுப்பிப்பைச் சேர்',
      'growth_stage': 'வளர்ச்சி நிலை',
      'no_growth_updates_yet': '🌱 இன்னும் வளர்ச்சி புதுப்பிப்புகள் இல்லை',
      'add_an_update_to_keep_track': 'உங்கள் பயிர் வளர்ச்சியை கண்காணிக்க ஒரு புதுப்பிப்பைச் சேர்க்கவும்.',
      'seed_sowing': 'விதை / விதைப்பு',
      'germination': 'முளைப்பு',
      'vegetative_growth': 'தாவர வளர்ச்சி',
      'flowering': 'பூக்கும்',
      'fruit_grain_development': 'பழம் / தானிய வளர்ச்சி',
      'maturity': 'முதிர்ச்சி',
      'harvest_ready': 'அறுவடைக்கு தயார்',
      'delete_update_confirm': 'இந்த வளர்ச்சி புதுப்பிப்பை நீக்க விரும்புகிறீர்களா?',
      'general_farm_reminder': 'பொதுவான பண்ணை நினைவூட்டல்',
      'delete_reminder_confirm': 'இந்த நினைவூட்டலை நீக்க விரும்புகிறீர்களா?',
      'upcoming': 'வரவிருக்கும்',
      'overdue': 'காலதாமதமானது',
      'completed': 'முடிந்தது',
      'mark_as_completed': 'முடிந்ததாக குறிக்கவும்',
      'delete': 'நீக்கு',
      'add_time': 'நேரம் சேர்',
      'clear_time': 'நேரத்தை அகற்று',
      'no_reminders_yet': '🔔 இன்னும் நினைவூட்டல்கள் இல்லை',
      'create_a_reminder': 'உங்கள் பண்ணை செயல்பாடுகளுக்கு நினைவூட்டலை உருவாக்கவும்.',
      'variety': 'ரகம்',
      'sowing_date': 'விதைத்த தேதி',
      'expected_harvest_date': 'எதிர்பார்க்கப்படும் அறுவடை தேதி',
      'farm_area': 'பண்ணை பரப்பளவு',
      'no_crops_added_yet': '🌱 பயிர்கள் எதுவும் சேர்க்கப்படவில்லை',
      'add_your_crops': 'உங்கள் பண்ணை தகவலை ஒழுங்கமைக்க உங்கள் பயிர்களைச் சேர்க்கவும்.',
      'remove_crop_confirm': 'இந்த பயிரை அகற்ற விரும்புகிறீர்களா?',
      'add_crop': '+ பயிர் சேர்',
      'edit_crop': '✏️ பயிர் திருத்து',
      'crop_name': 'பயிர் பெயர்',
      'save': 'சேமி',
      'cancel': 'ரத்து',
      'remove': '🗑️ அகற்று',
      'edit': '✏️ திருத்து',
      'use_current_location': '📍 தற்போதைய இருப்பிடத்தைப் பயன்படுத்தவும்',
      'location_unavailable': 'இருப்பிடம் கிடைக்கவில்லை',
      'location_saved': 'இருப்பிடம் சேமிக்கப்பட்டது',
      'location_updated': 'இருப்பிடம் புதுப்பிக்கப்பட்டது',
      'location_permission_denied': 'இருப்பிட அனுமதி மறுக்கப்பட்டது. தயவுசெய்து கைமுறையாக உள்ளிடவும்.',

      'village': 'கிராமம்',
      'district': 'மாவட்டம்',
      'state': 'மாநிலம்',
      'my_crops': 'என் பயிர்கள்',
      'remove_crop': 'அகற்று',
      'acres': 'ஏக்கர்',
      'hectares': 'ஹெக்டேர்',
      'irrigation_type': 'பாசன வகை',
      'farming_type': 'விவசாய வகை',
      'organic': 'கரிம',
      'conventional': 'பாரம்பரிய',
      'mixed': 'கலப்பு',
      'other': 'மற்றவை',
      'rainfed': 'மானாவாரி',
      'borewell': 'ஆழ்துளை கிணறு',
      'canal': 'கால்வாய்',
      'drip': 'சொட்டு நீர்',
      'sprinkler': 'தெளிப்பான்',
      'edit_profile': 'சுயவிவரத்தை திருத்து',
      'complete_profile_prompt': 'உங்கள் உழவர் சுயவிவரத்தை நிரப்பவும்\nRythuMitra-ஐ தனிப்பயனாக்க உங்கள் பண்ணை விவரங்களைச் சேர்க்கவும்.',
      'complete_profile': 'சுயவிவரத்தை நிறைவு செய்',
      'change_language': 'மொழியை மாற்றுக',

      'no_market_price_found': 'சந்தை விலை கிடைக்கவில்லை',
      'no_market_price_desc': 'இந்தப் பயிர் மற்றும் தேர்ந்தெடுக்கப்பட்ட இடத்திற்கு சந்தை விலை எதுவும் கிடைக்கவில்லை.',
      'try_again': 'மீண்டும் முயற்சிக்கவும்',
      'change_location': 'இடத்தை மாற்றவும்',
      'search_another_crop': 'வேறு பயிரைத் தேடவும்',
      'market_unavailable': 'சந்தை தகவல் தற்காலிகமாக கிடைக்கவில்லை.',
      // Backup & Restore
      'backup_restore': 'தரவு காப்புப்பிரதி & மீட்டமை',
      'create_backup': 'காப்புப்பிரதியை உருவாக்கு',
      'restore_backup': 'காப்புப்பிரதியை மீட்டமை',
      'backup_success': 'காப்புப்பிரதி வெற்றிகரமாக உருவாக்கப்பட்டது',
      'restore_farm_data': 'உங்கள் பண்ணை தரவை மீட்டமைக்கவும்',
      'restoring_data': 'உங்கள் பண்ணை தரவை மீட்டமைக்கிறது...',
      'invalid_backup_file': 'தவறான காப்புப்பிரதி கோப்பு',
      'continue_btn': 'தொடரவும்',
      'backup_version': 'காப்புப்பிரதி பதிப்பு',
      'backup_date': 'காப்புப்பிரதி தேதி',
      'backup_warning': 'இந்த காப்புப்பிரதி உங்கள் தற்போதைய பண்ணை தரவை மாற்றக்கூடும்',
      'backup_not_supported': 'இந்த காப்புப்பிரதி RythuMitra இன் புதிய பதிப்பைப் பயன்படுத்தி உருவாக்கப்பட்டது.',
      'restore_success': 'உங்கள் பண்ணை தரவு வெற்றிகரமாக மீட்டமைக்கப்பட்டது.',
      'backup_photos_not_included': 'குறிப்பு: பயிர் புகைப்படங்கள் காப்புப்பிரதியில் சேர்க்கப்படவில்லை.',
      // Emergency Help
      'emergency_help': 'அவசர உதவி',
      'important_contacts': 'முக்கிய தொடர்புகள்',
      'add_contact': 'தொடர்பைச் சேர்',
      'contact_name': 'தொடர்பு பெயர்',
      'phone_number': 'தொலைபேசி எண்',
      'contact_category': 'வகை',
      'contact_notes': 'குறிப்புகள்',
      'call_btn': 'அழைக்க',
      'edit_btn': 'திருத்து',
      'delete_btn': 'நீக்கு',
      'cancel_btn': 'ரத்துசெய்',
      'quick_access': 'விரைவான அணுகல்',
      'no_contacts_yet': 'முக்கிய தொடர்புகள் எதுவும் சேர்க்கப்படவில்லை.',
      'delete_contact_confirm': 'இந்த தொடர்பை நீக்க விரும்புகிறீர்களா?',
      'cat_agriculture_officer': 'வேளாண் அதிகாரி',
      'cat_veterinary_help': 'கால்நடை உதவி',
      'cat_family': 'குடும்பம்',
      'cat_friend': 'நண்பர்',
      'cat_medical_help': 'மருத்துவ உதவி',
      'cat_emergency': 'அவசரம்',
      'cat_other': 'மற்றவை',
    }
  };

  String translate(String key) {
    if (_localizedValues.containsKey(localeName)) {
      if (_localizedValues[localeName]!.containsKey(key)) {
        return _localizedValues[localeName]![key]!;
      }
    }
    // Fallback to English
    return _localizedValues['en']![key] ?? key;
  }
}
